### ISSUE TITLE
GraphFM-IB发布时间

### ISSUE THREAD

**Issue by er123dcfv** [Oceanusity/AI4DFT#1]
请问GraphFM-IB预计什么时间能够发布？文章中说的DIG项目中暂时还未更新。麻烦您是够方便给的大概时间？因为我已经开题答辩写了这个算法并且通过了，但是刚发现还未发布，希望您能提供一个时间范围，以便我做后续计划。非常感谢您！

**Comment by Oceanusity** [comment]
Please email me for information, and my email is haiyang@tamu.edu.

Link: https://github.com/divelab/DIG/tree/dig-stable/examples/lsgraph/GraphFMIB

**Comment by er123dcfv** [comment]
收到，非常感谢。
